import Link from "next/link"
import { ArrowRight, Check, MapPin, Gauge, ShieldCheck } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Container } from "@/components/layout/container"
import { rdpPlans, locations } from "@/data/rdp"

export function ProductHero({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <section className="relative overflow-hidden border-b border-border/60"><div className="pointer-events-none absolute inset-x-0 top-0 h-72 bg-accent/10 blur-3xl" /><Container className="relative py-20 sm:py-28"><p className="font-mono text-xs uppercase tracking-[0.28em] text-accent">{eyebrow}</p><h1 className="mt-5 max-w-4xl text-balance text-5xl font-semibold tracking-tight sm:text-7xl">{title}</h1><p className="mt-6 max-w-2xl text-pretty text-lg leading-relaxed text-muted-foreground">{description}</p></Container></section>
}

export function PlanGrid() {
  return <Container className="grid gap-5 py-16 md:grid-cols-3">{rdpPlans.map((plan) => <article key={plan.id} className="glass glass-hover flex flex-col rounded-2xl p-6"><div className="flex items-center justify-between gap-3"><p className="font-mono text-xs uppercase tracking-wider text-accent">{plan.badge}</p><span className="rounded-full bg-accent/10 px-2 py-1 text-xs text-accent">{plan.location}</span></div><h2 className="mt-5 text-2xl font-semibold">{plan.name}</h2><p className="mt-2 text-sm text-muted-foreground">Stable remote access for railway booking workflows.</p><div className="mt-7 flex items-end gap-1"><span className="text-4xl font-semibold">₹{plan.price}</span><span className="pb-1 text-sm text-muted-foreground">/month</span></div><ul className="mt-7 flex flex-col gap-3 text-sm text-muted-foreground">{[plan.ram + " memory", plan.cpu, plan.storage, plan.bandwidth + " transfer"].map((item) => <li key={item} className="flex items-center gap-2"><Check className="size-4 text-accent" />{item}</li>)}</ul><Button asChild className="mt-8 w-full"><Link href={`/checkout?plan=${plan.id}`}>Deploy this plan <ArrowRight data-icon="inline-end" /></Link></Button></article>)}</Container>
}

export function LocationGrid() { return <Container className="grid gap-4 py-16 sm:grid-cols-2 lg:grid-cols-4">{locations.map((location) => <article key={location.code} className="glass rounded-2xl p-5"><div className="flex items-center justify-between"><MapPin className="size-5 text-accent" /><span className="size-2 rounded-full bg-accent" /></div><h2 className="mt-6 text-xl font-semibold">{location.city}</h2><p className="mt-1 font-mono text-xs text-muted-foreground">{location.code}</p><div className="mt-6 flex items-center justify-between border-t border-border pt-4 text-sm"><span className="text-muted-foreground">Typical latency</span><span className="font-mono text-accent">{location.latency}</span></div></article>)}</Container> }

export function TrustRail() { return <Container className="grid gap-4 py-12 sm:grid-cols-3"><div className="glass rounded-xl p-5"><Gauge className="size-5 text-accent" /><p className="mt-4 font-semibold">Low-latency routes</p><p className="mt-1 text-sm text-muted-foreground">India-first network paths built for responsive sessions.</p></div><div className="glass rounded-xl p-5"><ShieldCheck className="size-5 text-accent" /><p className="mt-4 font-semibold">Session stability</p><p className="mt-1 text-sm text-muted-foreground">Keep your remote workspace ready through peak windows.</p></div><div className="glass rounded-xl p-5"><MapPin className="size-5 text-accent" /><p className="mt-4 font-semibold">Four live locations</p><p className="mt-1 text-sm text-muted-foreground">Choose the node nearest to your booking workflow.</p></div></Container> }
